config/routes.rb
HikingStats::Application.routes.draw do
  resources :messages

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'reset_password' => 'users#password', :as => :password
  match 'search' => 'trips#search', :as => :search
  match 'advanced_search' => 'trips#advanced_search', :as => :advanced_search
  match 'map' => 'routes#new'
  match 'about' => 'static#about'
  match 'privacy_policy' => 'static#privacy_policy'
  match 'donate' => 'static#donate'

  resources :user_sessions
  resources :users do
    resources :hikes, controller: 'trips', as: 'trips'
    resources :posts
    resources :forecasts
    resources :notifications
  end
  resources :hikes, as: 'trips', controller: 'trips' do
    resources :comments
    resources :photos
    resources :hearts
  end
  resources :map_layers
  resources :routes
  resources :photos
  resources :forecasts
  resources :comments
  resources :notifications do
    get 'read', on: :member
  end


  # legacy route support
  match '/with(/*path)' => redirect{|params| "/users/#{params[:path]}".chomp("/") }
  match '/:controller(/:action(/:id))'
  root :to => 'static#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :trip
	belongs_to :user
	validates_presence_of :body, :on => :create, :message => "can't be blank"
  has_many :notifications, as: :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authorize

	def index
		@comments = Comment.where(:user_id => current_user.id)
	end

  def create
		@comment = Comment.new(params[:comment])
		if @comment.save
			redirect_to user_trip_path(@comment.trip.user, @comment.trip) + "#comments"
		end
  end

	def edit
		@comment = Comment.find(params[:id])
		@trip = @comment.trip
		redirect_to :back unless current_user.id == @comment.user_id
	end

	def update
		@comment = Comment.find(params[:id])
		@trip = @comment.trip
		redirect_to :back unless current_user.id == @comment.user_id
		if @comment.update_attributes(params[:comment])
			redirect_to "#{user_trip_path(@trip.user, @trip)}#comment_#{@comment.id}"
		else
			render :action => "edit"
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		flash[:notice] = "Deleted comment."
		redirect_to :back
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<div class="column meta">
		<div class="profile-photo"><a href="<%= user_trips_path(comment.user) %>" class="micro-profile-photo">
			<%= image_tag(comment.user.avatar.url(:micro)) unless comment.user.avatar_file_name.blank? rescue nil %>
		</a></div>
		<p><%= link_to comment.user.name, user_trips_path(comment.user) rescue "[deleted user]" %><br />
		<%= comment.created_at.strftime("%B %e, %Y") %></p>
	</div>
	<div class="column last body">
		<%= markdown h(comment.body) %>
		
		<%= link_to(image_tag("edit.png", :alt => "edit", :class => "edit"), edit_trip_comment_path(@trip, comment)) if comment.user_id == current_user.try(:id) && comment.created_at > 1.week.ago rescue nil%>
	</div>
	<div class="clearer"></div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@trip, @comment]) do |f| %>
	<%= f.text_area :body %>
	<%= f.hidden_field :trip_id %>
	<%= f.hidden_field :user_id %>
	<%= f.submit "Add your comment", :class => "super awesome large button" %>
<% end %>

app/views/comments/edit.html.erb
<% page_title "Edit your comment" %>

<h1>Now Editing</h1>
<p class="note">In response to &ldquo;<%= @trip.name %>&rdquo;</p>
<div class="column">
<%= semantic_form_for([@trip, @comment], url: hike_comment_path(@trip, @comment)) do |f| %>
<%= f.inputs do %>
	<%= f.input :body, :label => "Comment" %>
	<%= f.input :trip_id, :as => :hidden %>
	<%= f.input :user_id, :as => :hidden %>
<% end %>
<%= f.actions do %>
	<%= f.submit "Edit your comment", :class => "super awesome large button" %>
	<%= link_to "or cancel", :back %>
<% end %>
<% end %>
</div>

app/views/comments/index.html.erb
<% page_title "Your Comments" %>