config/routes.rb
HikingStats::Application.routes.draw do
  resources :messages

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'reset_password' => 'users#password', :as => :password
  match 'search' => 'trips#search', :as => :search
  match 'advanced_search' => 'trips#advanced_search', :as => :advanced_search
  match 'map' => 'routes#new'
  match 'about' => 'static#about'
  match 'privacy_policy' => 'static#privacy_policy'
  match 'donate' => 'static#donate'

  resources :user_sessions
  resources :users do
    resources :hikes, controller: 'trips', as: 'trips'
    resources :posts
    resources :forecasts
    resources :notifications
  end
  resources :hikes, as: 'trips', controller: 'trips' do
    resources :comments
    resources :photos
    resources :hearts
  end
  resources :map_layers
  resources :routes
  resources :photos
  resources :forecasts
  resources :comments
  resources :notifications do
    get 'read', on: :member
  end


  # legacy route support
  match '/with(/*path)' => redirect{|params| "/users/#{params[:path]}".chomp("/") }
  match '/:controller(/:action(/:id))'
  root :to => 'static#home'
end

app/models/heart.rb
class Heart < ActiveRecord::Base
	belongs_to :user
	belongs_to :trip
	default_scope :order => "created_at DESC"
	
	def self.personal(trip, user)
		self.find_or_initialize_by_trip_id_and_user_id(trip.id, user.try(:id))
	end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
	before_filter :authorize
  def create
		@trip = Trip.find(params[:trip_id])
		if current_user.id != @trip.user.id
			@heart = Heart.find_or_create_by_user_id_and_trip_id(:user_id => current_user.id, :trip_id => params[:trip_id])
			@hearts = @trip.hearts
		else
			render "nope"
		end
  end

  def destroy
		@heart = Heart.find_by_user_id_and_trip_id(current_user.id, params[:trip_id])
		@trip = @heart.trip
		@hearts = @trip.hearts
		@heart.destroy
  end
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/views/hearts/_form.html.erb
<div id="heart_<%= trip.id %>" class="heart">
<% if current_user %>
	<% heart = Heart.personal(trip, current_user) %>
	<% if heart.persisted? %>
		<%= link_to trip_heart_path(trip,heart), :method => :delete, :remote => true do %>
			<%= image_tag("heart.png", :alt => "Unheart this trip") %>
		<% end %>
	<% else %>
		<%= form_for [trip, heart], :remote => true do |f| %>
			<%= image_submit_tag "heart_bw.png", :title => "Heart this trip!" %>
		<% end %>
	<% end %>
<% else %>
	<%= link_to image_tag("heart_bw.png"), login_path %>
<% end %>
<%= trip.hearts.count if trip.hearts.count > 0 %>
</div>

app/views/hearts/_hearts.html.erb
<div id="hearted">
<% unless @hearts.blank? %>
	<%= @hearts.map{|h| link_to(h.user.try(:name), user_trips_path(h.user)) }.to_sentence.html_safe %> 
	<%= @hearts.size == 1 ? "hearts" : "heart" %> this trip.
<% end %>
</div>

app/views/hearts/create.js.erb
$("#heart_<%= @trip.id %>").replaceWith('<%= escape_javascript(render :partial => "form", :locals => { :trip => @trip }) %>');
$("#hearted").replaceWith('<%= escape_javascript(render "hearts/hearts") %>').effect("highlight", {}, 500);

app/views/hearts/destroy.js.erb
$("#heart_<%= @trip.id %>").replaceWith('<%= escape_javascript(render :partial => "form", :locals => { :trip => @trip }) %>');
$("#hearted").replaceWith('<%= escape_javascript(render "hearts/hearts") %>').effect("highlight", {}, 500);

app/views/hearts/nope.js.erb
$("#heart_<%= @trip.id %> form").effect("shake", {times: 3, distance: 3, easing: "easeInOutQuad"}, 100)