config/routes.rb
HikingStats::Application.routes.draw do
  resources :messages

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'reset_password' => 'users#password', :as => :password
  match 'search' => 'trips#search', :as => :search
  match 'advanced_search' => 'trips#advanced_search', :as => :advanced_search
  match 'map' => 'routes#new'
  match 'about' => 'static#about'
  match 'privacy_policy' => 'static#privacy_policy'
  match 'donate' => 'static#donate'

  resources :user_sessions
  resources :users do
    resources :hikes, controller: 'trips', as: 'trips'
    resources :posts
    resources :forecasts
    resources :notifications
  end
  resources :hikes, as: 'trips', controller: 'trips' do
    resources :comments
    resources :photos
    resources :hearts
  end
  resources :map_layers
  resources :routes
  resources :photos
  resources :forecasts
  resources :comments
  resources :notifications do
    get 'read', on: :member
  end


  # legacy route support
  match '/with(/*path)' => redirect{|params| "/users/#{params[:path]}".chomp("/") }
  match '/:controller(/:action(/:id))'
  root :to => 'static#home'
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
  end
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-17121900-4']);_gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title><%= page_title %> | Went Hiking</title>
<meta name="description" content="<%= yield(:meta) || 'Hiking &amp; backpacking trip logs made easy. View local trail descriptions, trip reports, and photos, and create your own hiking blog to record your trips into thw wilderness.' %>" />
<%= stylesheet_link_tag :application %>
<script src="http://maps.google.com/maps/api/js?sensor=false&amp;v=3.4&amp;libraries=geometry&amp;language=en" type="text/javascript"></script>
<%= javascript_include_tag :application %>
<%= yield :head %>
<%= render :partial => 'layouts/analytics' %>
</head>
<body>
	<div id="navigation">
	<div class="container">
		<%= link_to(image_tag("went_hiking.png", alt: "Went Hiking"), root_path, id: "logo") %>
		<div class="nav">
		<% if current_user.blank? %>
			<%= link_to "Map", map_path, id: "map_link" %>
      <%= link_to "Join the community", new_user_path, id: "add_link" %>
			<%= link_to "Log in", login_path, id: "profile_link", onclick: "$('#login_form').fadeToggle(75);$('#user_session_email').focus();return false" %>
			<% @user_session = UserSession.new %>
			<%= render "user_sessions/popup" %>
		<% else %>
			<%= link_to "Add trip", new_user_trip_path(current_user), id: "add_link" %>
			<%= link_to "Profile", user_trips_path(current_user), id: "profile_link" %>
			<%= link_to "Settings", edit_user_path(current_user), id: "settings_link" %>
			<%= link_to "Forecasts", user_forecasts_path(current_user), id: "forecasts_link" %>
			<%= link_to "Map", map_path, id: "map_link" %>
      <%= link_to current_user.notifications.unread.size, user_notifications_path(current_user), id: "notifications_badge" %>
			<%= link_to "Log out", logout_path, id: "logout_link" %>
		<% end %>
		<%= form_tag "/search", method: :get, id: "search" do %>
			<%= text_field_tag :q, nil, placeholder: "Search…" %>
			<%= image_submit_tag "magnifier.png", id: "search_link" %>
		<% end %>
		</div>
	</div>
	</div>
	<%= yield :before_header %>
			<% if content_for? :header %>
			<div id="header">
			<div class="container">
				<%= yield :header %>
			<div class="clearer"></div>
			</div>
			</div>
			<% end %>
	<%= yield :map %>
	<div id="content">
	<div class="container">
			<%- flash.each do |name, msg| -%>
	      		<%= content_tag :div, msg, :class => "flash #{name}" %>
	    	<%- end -%>
			<%= yield %>
	</div>
	<div class="clearer"></div>
	</div>
	<div id="footer">
		<div class="container">
		<div class="column">
			<p>
				<iframe src="http://www.facebook.com/plugins/like.php?app_id=151577808250088&amp;href=http%3A%2F%2Fwenthiking.com&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:21px; display:inline-block" allowTransparency="true"></iframe>
				<g:plusone size="medium" href="http://wenthiking.com"></g:plusone>
			</p>

			<p>Went Hiking &copy; 2010. All rights reserved. All photos &copy; their respective owners. Photos may not be used or modified without express written consent of the author.<br /> <%= link_to "About", "/about" %> | <%= link_to "Privacy Policy", "/privacy_policy" %></p>
		</div>
		<div class="column last">
			<p>
				<a href="http://twitter.com/wenthiking" class="twitter-follow-button" data-show-count="true">Follow @wenthiking</a>
				<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
			</p>
			<p>This website was lovingly crafted by <a href="http://kaiuhl.com">Kyle Meyer</a>, a web designer, developer, and backpacker in Portland, Oregon. Question or comment? Please <%= mail_to "kyle@wenthiking.com", "email me." %></p>
		</div>
		<div class="clearer"></div>
		</div>
	</div>
	<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
</body>
</html>

app/views/layouts/email.html.erb
<div style="
	font-family:arial,helvetica,sans-serif;
	font-size:14px;
	color:#222;
	line-height:1.5;
	
	margin:20px 10%;

">
	<%= yield %>
	<div style="
		font-size:9px;
		color:#999;
		margin-top:20px;
		padding-top:20px;
		border-top:1px solid #ccc
	">

	</div>
</div>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title><%= page_title %> | Went Hiking</title>
<meta name="description" content="<%= yield(:meta) || 'Hiking &amp; backpacking trip logs made easy.' %>" />
<%= stylesheet_link_tag :application %>
<script src="http://maps.google.com/maps/api/js?sensor=false&amp;v=3.4&amp;libraries=geometry&amp;language=en" type="text/javascript"></script>
<%= javascript_include_tag :application %>
<style type="text/css">
	.day {
		float:left;
		width:75px;
		margin-right:10px;
		position:relative;
		text-align:center;
	}
	.day .weather_summary {
		color:#999;
		font-size:75%;
		height:35px;
	}
	.day .high {
		color:#671D21;
		font-size:125%;
	}
	.day .low {
		color:#5FA8CC;
	}
	.day .forecast_title {
		font-weight:bold;
		margin-bottom:10px;
	}
</style>
<%= yield :head %>
<%= render :partial => 'layouts/analytics' %>
</head>
<body>
	<div id="navigation">
	<div class="container">
		<%= link_to(image_tag("went_hiking.png", :alt => "Went Hiking"), root_path, :id => "logo") %>
		<div class="nav">
			<a onclick="beef.polylines.startDrawing();return false;" href="#">
				<%= image_tag "pencil_add.png", alt: "start drawing", title: "start drawing" %>
				draw path
			</a>
			<a onclick="beef.polylines.stopDrawing();return false;" href="#">
				<%= image_tag "pencil_delete.png", alt: "stop drawing", title: "stop drawing" %>
				stop drawing
			</a>
			<a onclick="beef.polylines.stepBack();return false;" href="#">
				<%= image_tag "arrow_undo.png", alt: "undo", title: "undo" %>
				undo
			</a>
			<!-- <a onclick="$('form').first().submit();return false;" href="">
					<%= image_tag "disk.png", alt: "save", title: "save" %>
					save
				</a> -->
			
			<span class="nav-unit">
				<input type="search" id="geolocate" placeholder="Search the map…" />
				<%= image_submit_tag "magnifier.png", :id => "search_link" %>
			</span>
		</div>
	</div>
	</div>
	<%- flash.each do |name, msg| -%>
     		<%= content_tag :div, msg, :id => "flash_#{name}" %>
   	<%- end -%>
	<%= yield %>
</body>
</html>

app/views/layouts/small.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title><%= page_title %> | Went Hiking</title>
<%= stylesheet_link_tag :application %>
<script src="http://maps.google.com/maps/api/js?sensor=false&amp;v=3.4&amp;libraries=geometry&amp;language=en" type="text/javascript"></script>
<%= javascript_include_tag :application %>
<style type="text/css" media="screen">
	
</style>
<script type="text/javascript">
$(document).ready(function(){
	$("#small_container").draggable();
	$("#user_session_email").select().focus();
	beef.defaults.zoom 			= 5;
	beef.defaults.lat			= 39.48;
	beef.defaults.lng			= -98.18;
	beef.defaults.doubleclick 	= true;
	beef.defaults.scrollwheel 	= true;
	beef.load();
	topo();
})
</script>
<%= render :partial => 'layouts/analytics' %>
</head>
<body style="background:black">
	<div id="map" style="width:100%;height:100%;position:absolute;z-index:0;top:0;opacity:1"></div>
	<div class="container small box" id="small_container">
	<div id="navigation">
		<%= link_to(image_tag("went_hiking.png", :alt => "Went Hiking"), root_path) %>
	</div>
	<%- flash.each do |name, msg| -%>
     		<%= content_tag :div, msg, :id => "flash_#{name}" %>
   	<%- end -%>
	<%= yield %>
	</div>
</body>
</html>